# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
dist: xenial
os: linux

env:
  global:
    # Use non-interactive backend
    - MPLBACKEND: Agg
    - CYTHON_TRACE: 1
    - NUMPYSPEC=numpy
    - MATPLOTLIBSPEC=matplotlib
    - CYTHONSPEC=cython

jobs:
  include:
    - arch: arm64
      os: linux
      python: 3.7
      dist: bionic # travis-ci/travis-ci/issues/9815
      env:
        - NUMPYSPEC=numpy
        - MATPLOTLIBSPEC=matplotlib
        - CYTHONSPEC=cython
        - USE_SDIST=1
cache: pip

before_install:
  - uname -a
  - df -h
  - ulimit -a
  - ccache -s
  - which python; python --version
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libatlas-base-dev; fi
  - pip install --upgrade pip wheel setuptools
  # Set numpy version first, other packages link against it
  - pip install $NUMPYSPEC
  - pip install $MATPLOTLIBSPEC
  - pip install $CYTHONSPEC
  - pip install pytest pytest-cov coverage codecov
  - set -o pipefail
  - if [ "${USE_WHEEL}" == "1" ]; then pip install wheel; fi
  - if [ "${USE_SCIPY}" == "1" ]; then pip install scipy; fi
  - |
    if [ "${REFGUIDE_CHECK}" == "1" ]; then
        pip install sphinx numpydoc
    fi

script:
  # Define a fixed build dir so next step works
  - |
    if [ "${USE_WHEEL}" == "1" ]; then
        # Need verbose output or TravisCI will terminate after 10 minutes
        pip wheel . -v
        pip install PyWavelets*.whl -v
        pushd demo
        pytest --pyargs pywt
        if [[ "${TRAVIS_CPU_ARCH}" != "arm64" ]]; then
        python ../pywt/tests/test_doc.py;
        fi
        popd
    elif [ "${USE_SDIST}" == "1" ]; then
        python setup.py sdist
        # Move out of source directory to avoid finding local pywt
        pushd dist
        pip install PyWavelets* -v
        pytest --pyargs pywt
        if [[ "${TRAVIS_CPU_ARCH}" != "arm64" ]]; then
        python ../pywt/tests/test_doc.py;
        fi
        popd
    elif [ "${REFGUIDE_CHECK}" == "1" ]; then
        pip install -e . -v
        python util/refguide_check.py --doctests
    else
        CFLAGS="--coverage" python setup.py build --build-lib build/lib/ --build-temp build/tmp/
        CFLAGS="--coverage" pip install -e . -v
        pushd demo
        pytest --pyargs pywt --cov=pywt --cov-config=../.coveragerc
        cp .coverage ..
        popd
    fi

after_success:
  - codecov
  # Travis CI has old gcov, needs object dir explicitly specified
  - gcov --object-directory build/tmp/pywt/_extensions/c/ build/tmp/pywt/_extensions/c/*.o
  - bash <(curl -s https://codecov.io/bash)
